```{r}
source("Rscripts/utils.R")
#library(devtools)
#devtools::install_github("mrvollger/mrvplot")
#library(mrvplot)
```

```{r}
metadata=fread(cmd="wget -O - https://docs.google.com/spreadsheets/d/e/2PACX-1vS179_OCRBe8JEuPWh7QWnhNI5ZwpoydUUjpZXMzFTGcCf6ERDZDUMVhN04UpX32wDOo17SGtkL4Xsy/pub?output=csv", header=T, fill=TRUE) %>% 
    as.tibble() 


cn_f = metadata %>% filter(Datatype =="CN_T") %>% pull(Location)
cn_cross_f = metadata %>% filter(Datatype =="CN_cross_T") %>% pull(Location)
asm_f = metadata %>% filter(Datatype =="assembly") %>% pull(Location)
bl_peaks_f = metadata %>% filter(Datatype =="FIRE_peaks_BL") %>% pull(Location)
bl_pileup_f = metadata %>% filter(Datatype =="FIRE_pileup_BL") %>% pull(Location)
t_peaks_f = metadata %>% filter(Datatype =="FIRE_peaks_T") %>% pull(Location)
t_pileup_f = metadata %>% filter(Datatype =="FIRE_pileup_T") %>% pull(Location)
snv_f = metadata %>% filter(Datatype =="SNV_calls") %>% pull(Location)
indel_f = metadata %>% filter(Datatype =="Indel_calls") %>% pull(Location)
hap_vcf_f = metadata %>% filter(Datatype =="hap_vcf") %>% pull(Location)
```

```{r}
LOD=0.10
MIN_COV = 30
fai = fread(glue("{asm_f}.fai"), header=F, col.names=c("chrom", "size", "offset", "line_bases", "line_width"))
cn = my_read_bed(cn_f) 
cn_cross = my_read_bed(cn_cross_f)
bl_peaks = my_read_bed(bl_peaks_f) %>% filter(fire_coverage/coverage > LOD)
t_peaks = my_read_bed(t_peaks_f) %>% filter(fire_coverage/coverage > LOD)

peak_union = bed_merge(bind_rows(list(bl_peaks, t_peaks))) %>%
    mutate(
        haplotype = case_when(
            grepl("haplotype1", chrom) ~ "H1",
            grepl("haplotype2", chrom) ~ "H2",
            TRUE ~ "UNK"
        )
    )
rand_windows = bed_shuffle(peak_union, seed=42, genome=fai) %>%
    mutate(
        haplotype = case_when(
            grepl("haplotype1", chrom) ~ "H1",
            grepl("haplotype2", chrom) ~ "H2",
            TRUE ~ "UNK"
        )
    )

snv = read_vcf(snv_f) %>% mutate(chrom=gsub("^chr", "", chrom))
indel = read_vcf(indel_f) %>% mutate(chrom=gsub("^chr", "", chrom))
hap_vcf = read_vcf(hap_vcf_f) %>% mutate(chrom=gsub("^chr", "", chrom))
hap_vcf
```

# joint cn
```{r}
bind_rows(
    list(
        cn=cn,
        cn_cross=cn_cross
    ),
    .id="source"
) %>%
    filter(!is.na(CN)) %>%
    select(chrom, start, end, CN, source) %>%
    mutate(
        # strip whitespace from CN
        CN=gsub("\\s+", "", CN),
        CN=case_when(
            CN == "DEL" ~ 0,
            CN == "CN1" ~ 1,
            CN == "CN2" ~ 2,
            CN == "CN3" ~ 3,
            CN == "CN4" ~ 4,
            CN == ">CN4" ~ 5,
            TRUE ~ 10000
        )
    ) %>% 
    arrange(chrom, start, end) %>%
    fwrite("tmp.joint.cn.bed", sep="\t", col.names=F, row.names=F, quote=F)

# run this
glue('bedtools unionbedg -i <(grep -wv cn_cross tmp.joint.cn.bed | cut -f 1-4) <(grep -w  cn_cross tmp.joint.cn.bed | cut -f 1-4) > tmp.cn.bed')
cn_joint=fread("tmp.cn.bed")
names(cn_joint)=c("chrom", "start", "end", "CN", "CN_cross")
```


# only read files that intersect with the union of peaks
```{r}
load = TRUE
if (load) {
    # load in the bl_pileup and t_pileup from rds files
    bl_pileup = readRDS("Rdata/bl_pileup.rds")
    t_pileup = readRDS("Rdata/t_pileup.rds")
} else {
    # write to bed
    peak_union %>% fwrite("tmp-peak-union.bed", sep="\t", col.names=F, row.names=F, quote=F) 
    # my_read_bed with bedtools intersect
    bl_pileup = my_read_bed(cmd=glue("tabix --cache 10000 -@ 8 -T tmp-peak-union.bed -h {bl_pileup_f}"))
    t_pileup = my_read_bed(cmd=glue("tabix --cache 10000 -@ 8 -T tmp-peak-union.bed -h {t_pileup_f}"))
    # save bl_pileup and t_pileup as rds files
    bl_pileup %>% saveRDS("Rdata/bl_pileup.rds")
    t_pileup %>% saveRDS("Rdata/t_pileup.rds")
}
```


# make the merged dataset
```{r}
if(load){
    bl_vs_t_dataset = fread("Tables/BL-vs-T-dataset.tbl.gz", sep="\t", header=T)
    bl_vs_t_dataset_filtered = fread("Tables/BL-vs-T-dataset-filtered.tbl.gz", sep="\t", header=T)
} else{
    bl_vs_t_dataset = bind_rows(
            list(
                real=peak_union,
                shuffle=rand_windows
            ),
            .id="source"
        ) %>%
        #head(1000) %>%
        bed_map(
            cn,
            cn_call = CN,
            n_cn_calls = n(),
        ) %>%
        bed_map(
            cn_cross,
            cn_cross_call = CN,
            n_cn_cross_calls = n(),
        ) %>%
        bed_map(
            bl_pileup,
            bl_fire_h1 = fire_coverage_H1[which.max(score)],
            bl_fire_h2 = fire_coverage_H2[which.max(score)],
            bl_cov_h1 = coverage_H1[which.max(score)],
            bl_cov_h2 = coverage_H2[which.max(score)],
            bl_fire = fire_coverage[which.max(score)],
            bl_cov = coverage[which.max(score)],
        ) %>%
        bed_map(
            t_pileup,
            t_fire_h1 = fire_coverage_H1[which.max(score)],
            t_fire_h2 = fire_coverage_H2[which.max(score)],
            t_cov_h1 = coverage_H1[which.max(score)],
            t_cov_h2 = coverage_H2[which.max(score)],
            t_fire = fire_coverage[which.max(score)],
            t_cov = coverage[which.max(score)]
        ) %>%
        bed_map(
            snv,
            snv_count = n(),
        ) %>%
        bed_map(
            indel,
            indel_count = n(),
        ) %>%
        bed_map(
            hap_vcf,
            n_hap_snv = n(),
        ) %>%
        bed_map(
            bl_peaks,
            n_bl_peaks = n(),
            is_bl_peak = n() > 0,
        ) %>%
        bed_map(
            t_peaks,
            n_t_peaks = n(),
            is_t_peak = n() > 0,
        ) %>%
        replace_na(list(
            snv_count = 0,
            n_hap_snv = 0,
            indel_count = 0,
            n_bl_peaks = 0,
            n_t_peaks = 0,
            is_bl_peak = FALSE,
            is_t_peak = FALSE
        )) %>%
        mutate(
            hap_diff_bl = bl_fire_h1/bl_cov_h1 - bl_fire_h2/bl_cov_h2,
            hap_diff_t = t_fire_h1/t_cov_h1 - t_fire_h2/t_cov_h2,
            bl_frac_acc = bl_fire/bl_cov,
            t_frac_acc = t_fire/t_cov,
        ) %>%
        ungroup() %>%
        bed_map(
            snv %>% ungroup(),
            n_somatic_snv = n(),
            is_somatic_snv = n() > 0,
        ) %>%
        replace_na(list(
            n_somatic_snv = 0,
            is_somatic_snv = FALSE
        )) %>%
        mutate(
            other_hap_is_normal_cn = case_when(
                cn_cross_call == "CN1" ~ TRUE,
                TRUE ~ FALSE,
            )
        )

    sum(bl_vs_t_dataset$is_somatic_snv)
    table(bl_vs_t_dataset$cn_call)
    table(bl_vs_t_dataset$cn_cross_call)

    # save the datasets
    bl_vs_t_dataset %>% 
        fwrite("Tables/BL-vs-T-dataset.tbl.gz", sep="\t", row.names=F, quote=F)


    # the filtered dataset
    bl_vs_t_dataset_filtered = bl_vs_t_dataset %>%
        filter(
            bl_frac_acc > LOD | t_frac_acc > LOD,
        ) %>%
        filter(
            bl_cov_h1 > MIN_COV, bl_cov_h2 > MIN_COV,
        ) %>%
        filter(
            t_cov_h1 > MIN_COV, t_cov_h2 > MIN_COV,
        ) %>%
        # do a fishers test for the haplotype differences
        rowwise() %>%
        mutate(
            hap_diff_bl_p_value = fisher.test(
                matrix(c(bl_fire_h1, bl_fire_h2, bl_cov_h1-bl_fire_h1, bl_cov_h2-bl_fire_h2), nrow=2)
            )$p.value,
            hap_diff_t_p_value = fisher.test(
                matrix(c(t_fire_h1, t_fire_h2, t_cov_h1-t_fire_h1, t_cov_h2-t_fire_h2), nrow=2)
            )$p.value,
        ) %>%
        ungroup() %>%
        group_by(source) %>%
        mutate(
            hap_diff_bl_p_adjust = p.adjust(hap_diff_bl_p_value, method="BH"),
            hap_diff_t_p_adjust = p.adjust(hap_diff_t_p_value, method="BH")
        ) %>%
        data.table()

    # save the datasets
    bl_vs_t_dataset_filtered %>%
        fwrite("Tables/BL-vs-T-dataset-filtered.tbl.gz", sep="\t", row.names=F, quote=F)

}
```

# load the datasets
```{r}
```

```{r}
z=bl_vs_t_dataset_filtered %>%
    filter(
        #is_t_peak, is_bl_peak,
        #bl_frac_acc > LOD, t_frac_acc > LOD,
    ) %>%
    filter(source=="real") %>%
    #filter(other_hap_is_normal_cn) %>%
    filter(grepl("CN|DEL", cn_call)) %>%
    ggplot(aes(x=hap_diff_bl, y=hap_diff_t)) +
    geom_hex(bins=100) + scale_fill_distiller("", palette = "Spectral", trans="log10") +
    # mark ones that intersect with SNVs with a red cross
    geom_point(
        data=. %>% filter(snv_count > 0) %>% filter(F),
        aes(x=hap_diff_bl, y=hap_diff_t),
        color="darkred", 
        shape=3,
        alpha=0.4,
        size=0.01,
    ) +
    # add marginal histograms
    #geom_xsidehistogram(bins=100) +
    #geom_ysidehistogram(bins=100)+
    # make the aspect ratio 1:1
    coord_fixed() +
    scale_x_continuous(
        "Haplotype difference in accessibility (BL)",
        limits=c(-1, 1),
        label=percent,
    ) +
    scale_y_continuous(
        "Haplotype difference in accessibility (T)",
        limits=c(-1, 1),
        label=percent,
    ) +
    my_grid() 
my_ggsave("Figures/BL-vs-T-hap-diff.pdf", width=3, height=2)
z+facet_wrap(~cn_call) 
my_ggsave("Figures/BL-vs-T-hap-diff-facet.pdf", width=4, height=2.5)
```
